name: Core
version: '1.0'
main: DesDaugtMa.core.Core
api-version: '1.21'
description: 'Core-Plugin mit Spawn, Tablist und Stop-Schutz.'
commands:
  setspawn:
    description: Setzt den globalen Spawnpunkt.
    permission: core.admin
  core:
    description: System-Befehle (Reload).
    permission: core.admin