name: Core
version: '1.0-SNAPSHOT'
main: DesDaugtMa.core.Core
api-version: '1.21'
description: Essenzielle Funktionalitäten für den Server
commands:
  neustart:
    description: Startet den Server nach einer angegebenen Zeit neu.
    usage: /neustart <Sekunden>
    permission: core.restart
  setspawn:
    description: Setzt den globalen Spawnpunkt.
    usage: /setspawn
    permission: core.setspawn